@startuml

actor User
actor Server

User -> Server : Login
User -> Server : Create event, Turn on notification
User <- Server : Sends notification

newpage

User -> Server : Login
User -> Server : Create event
User -> Server : Modify event to push notification
User <- Server : Sends notification

newpage

User -> Server : Login
User -> Server : Search for event
User <- Server : 0 result
User -> Server : Corrects search
User <- Server : 1 result
User -> Server : Delete event

newpage

User -> Server : Login
User -> Server : Creates event in another timezone
Server -> User : Notifies user according to the set timezone

@enduml