@startuml

usecase (Create event) as UC1
usecase (Modify/Delete event) as UC2
usecase (Invite\nmultiple people) as UC3
usecase (Request feedback) as UC4
usecase (iPhone integration) as UC5
usecase (Give feedback\nto invite) as UC6
usecase ("Event repeat/duration") as UC7
usecase (Push notification) as UC8
usecase ("Search event") as UC9
usecase (Login) as UC10
usecase (Check date/time\navailability) as UC11
usecase ("Email\nnotification") as UC12
usecase (Set timezone) as UC13

actor :User:
actor :Others:
actor :Server:

User -down-> UC10
User -left-> UC9
UC10 .up.> UC9 : <<extend>>
User -up-> UC11
User -down-> UC1
User -down-> UC2
UC1 .> UC2 : <<extend>>
UC2 <|-down- UC3
UC2 <|-down- UC7
UC2 <|-down- UC8
UC2 <|-right- UC12
UC2 <|-up- UC13
UC3 .down.> UC4 : <<include>>
Others -up-> UC6
Server -down-> UC5
UC10 .> UC1 : <<extend>>
UC6 <. UC4 : <<extend>>

@enduml