@startuml

actor "CI\nA" as A
actor "OrgX\nB" as B
box " " #White
	actor Server
end box
actor Mail
actor Server2

A -> A : Create event
A -> Server
A -> Mail : Email to B
Mail -> B
B -> B : Accept event
B -> Server2
B -> Mail
Mail -> A
A -> Server : Update event

@enduml