@startuml

actor A
box " " #White
	actor Server
end box
actor Mail
actor "OrgX\nServer" as Server2

actor B
actor C

A -> A : Create event with B & C
A -> Server : Register event
A -> Mail : Sends email to B & C
Mail -> B
Mail -> C
B -> B : Accepts
B -> Server2
Server2 -> A : Sends answer
C -> C : Declines
C -> Server2
Server2 -> A : Sends answer
A -> Server : Updates event

@enduml
