@startuml

actor A
actor Admin
actor Server
actor Mail

Admin -> Server : Sends request to reset A's password
Server -> Admin : Sends confirmation
Mail -> A : Gets email to add new password
A -> Server : Registers new password

@enduml