@startuml

title Parallel Case
actor A
actor B
box " " #White
	actor Server
end box
actor Mail

A -> A : Create event with B
A -> Server : Register event
A -> Mail : Sends email to B
Mail -> B
A -> Server : Deletes the event
A <- Server : Sends confirmation
Mail -> B : Notifies about deletion

@enduml